<a href="https://colab.research.google.com/github/Kaizen-is/Data-Science/blob/main/02_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Scinece and AI Practicum**

Data Analytics

- Creating NumPy Arrays

In [ ]:
import numpy as np
data1 = [1, 1, 2, 4, 5 ] # python simple list
arr1 = np.array(data1) # numpy array
print(data1)
print(arr1)
print(type(arr1))

[1, 1, 2, 4, 5]
[1 1 2 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
data2 = ("Kaizen", "Jinwoo", "Kamado") # tuple
arr2 = np.array(data2) # tuple into array
print(type(data2), data2)
print(type(arr2))
arr2

<class 'tuple'> ('Kaizen', 'Jinwoo', 'Kamado')
<class 'numpy.ndarray'>


array(['Kaizen', 'Jinwoo', 'Kamado'], dtype='<U6')

- **Len of the Array**

In [ ]:
arr1.ndim # len of the first array

1

In [ ]:
arr2.ndim # len of the second array

1

- **Array of two or more dimensions**

In [ ]:
import numpy as np
data3 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]] # list in the list (nested list)
arr3 = np.array(data3)
print(type(arr3))
arr3

<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr3.ndim # len of the third array

2

- **Zeros and Ones**

In [ ]:
arr4 = np.zeros(shape = (2, 4)) # all elements are equal to zero
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones(shape = (3, 4)) # all elements are equal to one
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- **Shape and Size**

*shape and size give an info(array)*

In [ ]:
arr4.shape # (2, 4) (the length, all elements in 1 line)

(2, 4)

In [ ]:
arr5.size # amount of all elements in array

12

In [ ]:
arr6 = np.arange(2, 20, 2) # ([start], [end], [step])
arr6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr7 = np.arange(10) # each number from 0 to 9
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])