### Data Science and AI Practicum

Indexing with NumPy arrays

In [3]:
import numpy as np
arr = np.arange(10, 100, 10)
print(arr)


[10 20 30 40 50 60 70 80 90]


In [14]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
print(sliced_arr)

In [16]:
arr

array([10, 20, 30,  0,  0,  0,  0,  0,  0])

`copy`

In [18]:
import numpy as np
arr1 = np.arange(10, 100, 10)
sl_arr = arr1[3:5].copy()
sl_arr[:] = 0
print(sl_arr)
print(arr1)

[0 0]
[10 20 30 40 50 60 70 80 90]


3 Dimension array

In [26]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [1, 2, 3]]])
print(arr3)
arr3.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 1  2  3]]

 [[12 21 43]
  [67 54 76]]]


3

2 Dimension array

In [24]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(arr2)
arr2.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


2

In [37]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [1, 2, 3]]])
print(arr3)
print(arr3[1][0, 1])

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
8


In [38]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(arr2)
print(arr2[3][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
3
