### Data Science and AI Practicum

Data Analytics

- Boolean Indexing

In [2]:
import numpy as np
name = np.array(["Jinwoo", "Levi", "Bibi", "Igris", "Kaizen"])
print(name)

['Jinwoo' 'Levi' 'Bibi' 'Igris' 'Kaizen']


In [5]:
data = np.random.randn(5, 4)
print(data)

[[-0.41095094  0.07812253 -0.14648127 -1.60989532]
 [ 0.32775243 -1.14935557  0.35329017 -0.19633118]
 [ 0.6569732  -0.33714717  0.6004308  -0.41366443]
 [ 0.58372112  0.64435264 -1.0953189  -0.36372574]
 [ 0.6193372  -1.08903876  0.12776268  0.82180332]]


In [8]:
name == 'Bibi'

array([False, False,  True, False, False])

In [9]:
print(data[name == "Bibi"]) # info related to the name Bibi

[[ 0.6569732  -0.33714717  0.6004308  -0.41366443]]


In [10]:
print(data[name != 'Bibi']) # all info in the array except from 'Bibi'

[[-0.41095094  0.07812253 -0.14648127 -1.60989532]
 [ 0.32775243 -1.14935557  0.35329017 -0.19633118]
 [ 0.58372112  0.64435264 -1.0953189  -0.36372574]
 [ 0.6193372  -1.08903876  0.12776268  0.82180332]]


In [46]:
print(data[name == 'Kaizen', 2:4])

[[0.12776268 0.82180332]]


In [45]:
mask = (name == 'Jinwoo') | (name == "Kaizen")
data[mask]

array([[1.        , 0.07812253, 1.        , 1.        ],
       [0.6193372 , 1.        , 0.12776268, 0.82180332]])

In [15]:
mask

array([ True, False, False, False,  True])

In [44]:
data[data < 0] = 1  # turning all negative floats into 1
print(data)

[[1.         0.07812253 1.         1.        ]
 [0.32775243 1.         0.35329017 1.        ]
 [0.6569732  1.         0.6004308  1.        ]
 [0.58372112 0.64435264 1.         1.        ]
 [0.6193372  1.         0.12776268 0.82180332]]


### Practice

- Task 1

You are given a NumPy array representing the temperatures (in Celsius) recorded over 10 days. Your task is to:

Filter out temperatures above 30°C using boolean indexing.
Replace all negative temperatures with 0 (no negative temperatures allowed).
Count how many days had temperatures above 25°C.

In [43]:
import numpy as np
temps = np.array([22, 31, 15, -2, 28, 35, 40, 18, 25, 30]) # temperature for the last 10 days
# above 30
above = temps[temps >= 30] # getting temp above 30 or == 30
print(f"Temperatures above 30C: {above}")

temps[temps < 0] = 0 # replacing negative temp with 0
print(f"Negative replaced with 0: {temps} ")

# days above 25C
days = temps[temps > 25] # getting temp above 25 except from 25
print(f"Days above 25C: {len(days)}")

Temperatures above 30C: [31 35 40 30]
Negative replaced with 0: [22 31 15  0 28 35 40 18 25 30] 
Days above 25C: 5


- Task 2

You are given an array of temperatures (in Celsius) recorded over a week. Your goal is to filter out the days where the temperature was above the average temperature for the week.

In [42]:
import numpy as np
temps = np.array([15, 18, 21, 20, 22, 19, 17]) # Temperature during the week
average = temps.sum() / len(temps) # calculating the sum and dividing to the amount of elements

in_av = average.astype(np.int64) # changing dtype from float to integer
print(f"Average temperature during the week is: [{in_av}]")

above_av = temps[temps > in_av] # getting all temperatures above average
print(f"Days with above-average temperatures: {above_av}")

Average temperature during the week is: [18]
Days with above-average temperatures: [21 20 22 19]
