### Data Science and AI Practicum

Data Analytics

- Changing position of the arrar `Transpose` and changing positions of the vectors `Swapping axes`

In [ ]:
import numpy as np
A = np.arange(6).reshape(3, 2)
print(A)

[[0 1]
 [2 3]
 [4 5]]


`Transpose`

In [ ]:
print(A.T)

[[0 2 4]
 [1 3 5]]


In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

`Swapping axes`

swapaxes(axis1, axis2) swaps the specified axes of an array.

1D array → (n,) → only one axis (axis 0)

2D array → (rows, columns) → axis 0 = rows, axis 1 = columns

3D array → (depth, rows, columns) → axis 0 = depth, axis 1 = rows, axis 2 = columns

In [ ]:
print(A.swapaxes(1, 0))

[[0 2 4]
 [1 3 5]]


`.dot()`: numpy function

In [ ]:
np.dot(A, A.T) # multiplying 2 types of array

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

### Practice

- Task 1

Create a 1D NumPy array of 10 elements and rearrange it in reverse order without using slicing ([::-1]).

In [ ]:
import numpy as np
arr = np.arange(11)
print(arr)
print(arr[:: -1])

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


- Task 2

Given a 3×4 matrix, write a function to transpose it so that it becomes 4×3.

In [ ]:
import numpy as np
arr = np.arange(12).reshape(3, 4)
print(f"{arr}\n-----------------")
print(arr.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


- Task 3

Given a 3D array of shape (2, 3, 4), swap the first and last axes so that the shape becomes (4, 3, 2).

In [ ]:
import numpy as np
arr = np.arange(24).reshape(2, 3, 4)
print(f"{arr}\n{arr.shape}\n-----------------")
print(arr.swapaxes(0, 2))
print(arr.swapaxes(0, 2).shape)



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
-----------------
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)


- Task 4

Given two matrices: np.dot()

In [ ]:
import numpy as np
A = np.arange(9).reshape(3, 3)
print(A)
print("--------------")
B = np.random.randint(0, 20, size =(3, 3))
print(B)
print(f"--------------\nSum:\n{np.dot(A, B)}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------
[[13  3 12]
 [14 19  3]
 [12  5  6]]
--------------
Sum:
[[ 38  29  15]
 [155 110  78]
 [272 191 141]]
