### Data Science and AI Practicum

Data Analytics

### Universal Functions

Universal Functions: are the functions that work with one argument

`sqrt` `square` `exp` `log` `modf` `sign` `isnan`

In [ ]:
import numpy as np

In [2]:
import numpy as np
arr = np.arange(10) # array with numbers from 0 to 9
print(arr)

[0 1 2 3 4 5 6 7 8 9]


`square`

In [3]:
squ_arr = np.square(arr)
print(squ_arr)

[ 0  1  4  9 16 25 36 49 64 81]


----------------------

`sqrt`

In [8]:
sqrt_arr = np.sqrt(squ_arr)
sqrt_a = sqrt_arr.astype(np.int64)
print(sqrt_a)

[0 1 2 3 4 5 6 7 8 9]


----------------------

`exp`  exponential of the number

In [9]:
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


----------------------

`log`  log of the number

In [11]:
print(np.log(arr[1:]))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


----------------------

`modf` devides whole number and residual in to different arrays

In [13]:
arr1 = np.random.randn(6)
whole, residual = np.modf(arr1)
print(f"{arr1}\n{residual}\n{whole}")

[-0.14525353  1.08555956 -0.42422712 -0.25676034  1.23079842 -0.48439502]
[-0.  1. -0. -0.  1. -0.]
[-0.14525353  0.08555956 -0.42422712 -0.25676034  0.23079842 -0.48439502]


----------------------

`sign` if the sign of the number in the array "-" = -1, "+" = 1

In [14]:
print(arr1)
print(np.sign(arr1))

[-0.14525353  1.08555956 -0.42422712 -0.25676034  1.23079842 -0.48439502]
[-1.  1. -1. -1.  1. -1.]


----------------------

`isnan` if in the array NaN ist == True

In [17]:
print(np.isnan(arr1))
arr1[1] = np.NaN
print(arr1)
print(np.isnan(arr1))

[False False False False False False]
[-0.14525353         nan -0.42422712 -0.25676034  1.23079842 -0.48439502]
[False  True False False False False]


----------------------

### Binary Functions

Binary Functions: are the functions that work with two arguments

`add` `multiply` `maximum`

In [ ]:
import numpy as np

In [20]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)
print(arr2)
print(arr3)

[-0.93212313  0.83359683  0.49829334 -0.65477107  0.93836541 -1.96102797]
[ 1.73692989  2.02332864  0.14196082 -0.14305879  0.5305557   0.34415028]


----------------------

`add`

In [21]:
print(np.add(arr2, arr3))

[ 0.80480676  2.85692547  0.64025416 -0.79782986  1.46892111 -1.61687769]


----------------------

`multiply`

In [22]:
print(np.multiply(arr2, arr3)) # multiplying two arrays appropriate elements

[-1.61903252  1.68664034  0.07073813  0.09367075  0.49785512 -0.67488832]


----------------------

`maximum`

In [23]:
print(np.maximum(arr2, arr3)) # gets the biggest element among two appropriate elements in the array

[ 1.73692989  2.02332864  0.49829334 -0.14305879  0.93836541  0.34415028]


----------------------