### Data Science ans AI Practicum

Logical Condition Operators

`where` - condition operator

If `where` returns exact condition, 1 element from `xarray` will be taken but when False, 1 element from `yarray` will be taken

In [1]:
import numpy as np
xarray = np.array([1.1, 1.2, 1.3, 1.4])
yarray = np.array([2.1, 2.2, 2.3, 2.4])
condition = np.array([True, False, True, False])
result = np.where(condition, xarray, yarray) # if True, 1 element will be taken from xarray, if not yarray
print(result)

[1.1 2.2 1.3 2.4]


In [2]:
import numpy as np
array = np.random.randn(4, 4) # 4 to 4 aproximate array
print(f"{array}]\n---------------")
results = np.where(array<0, -2, 2) # given a condition, if element is negativ, will be replaced with -2, if not 2
print(results)

[[-0.52835446 -0.42452377 -0.68269255 -0.76086146]
 [ 0.86752034  0.54588468  0.43842146  1.28820209]
 [-0.75141846 -0.36237198 -0.27132108  0.28806791]
 [ 0.86559012 -0.51609847 -1.60361589  0.08462927]]]
---------------
[[-2 -2 -2 -2]
 [ 2  2  2  2]
 [-2 -2 -2  2]
 [ 2 -2 -2  2]]


### Practice

- Task 1

You are given a 2D NumPy array that contains both positive and negative numbers. Your task is to use np.where() to replace all negative numbers with their absolute values, while keeping positive numbers unchanged.

In [8]:
import numpy as np
ar = np.random.randn(9).reshape(3, 3)
print(f"{ar}\n------------")
result = np.where(ar < 0, -ar, ar) # if an element is negative, will be changed to its absolute number, if not stays the same
print(result)

[[ 0.02980529  0.8254751  -0.53983198]
 [ 0.47274465  0.40661361  0.17646231]
 [-1.12530925  0.11225724 -0.00236007]]
------------
[[0.02980529 0.8254751  0.53983198]
 [0.47274465 0.40661361 0.17646231]
 [1.12530925 0.11225724 0.00236007]]


- Task 2

Given a 1D NumPy array, categorize each element based on its value:

If the number is greater than 50, replace it with "High"
If the number is between 20 and 50, replace it with "Medium"
If the number is less than 20, replace it with "Low"

In [14]:
import numpy as np

arr = np.random.randint(101, size = (1, 11))
print(f"{arr}\n---------------")


results = np.where(arr <= 29, "Low",
                   np.where(arr <= 69, "Medium", "High")) # if < 29, changing to Low, if < 69, Medium, if neither(>70) High
print(results)

[[ 3 65 82  5 42  1 50 59 85 62 17]]
---------------
[['Low' 'Medium' 'High' 'Low' 'Medium' 'Low' 'Medium' 'Medium' 'High'
  'Medium' 'Low']]
