### Data Science and AI Practicum

Mathematik and Statistical Methods

### Mathematical

In [4]:
import numpy as np

arr1 = np.random.randint(0, 101, size = (1, 11))
arr2 = np.random.randint(0, 101, size = (1, 11))

print(arr1 + arr2)
print("---------------------------------------")
print(arr2 - arr1)
print("---------------------------------------")
print(arr1 * arr2)
print("---------------------------------------")
print(arr2 / arr1)
print("---------------------------------------")
print(arr1 ** 2)
print("---------------------------------------")
print(arr1 ** 0.5)

[[111  51  19  97 104 136  88  68  23  94 156]]
---------------------------------------
[[ 73  -7 -17 -45 -72   8 -36  12 -19 -82   6]]
---------------------------------------
[[1748  638   18 1846 1408 4608 1612 1120   42  528 6075]]
---------------------------------------
[[4.84210526 0.75862069 0.05555556 0.36619718 0.18181818 1.125
  0.41935484 1.42857143 0.0952381  0.06818182 1.08      ]]
---------------------------------------
[[ 361  841  324 5041 7744 4096 3844  784  441 7744 5625]]
---------------------------------------
[[4.35889894 5.38516481 4.24264069 8.42614977 9.38083152 8.
  7.87400787 5.29150262 4.58257569 9.38083152 8.66025404]]


Method `sum`

In [ ]:
arr3 = np.arange(16).reshape(4, 4)
print(arr3)


In [5]:
print(np.sum(arr3)) # sum of all elements in the array

563


In [11]:
arr3 = np.arange(16).reshape(4, 4)

print(np.sum(arr3, axis = 1)) # sum of all elements in the lines
print("\n")
print(np.sum(arr3, axis = 0)) # sum of all elements in the superiors

[ 6 22 38 54]


[24 28 32 36]


Method `mean` - an average value

In [19]:
average = np.sum(arr3) / arr3.size     # in python
print(average)

7.5


In [15]:
print(np.mean(arr3))                    # in numpy

7.5


In [21]:
ar = np.random.randn(16).reshape(4, 4)
print(ar)

[[ 1.04067975 -0.33587662  1.4297916   1.50545596]
 [ 0.85648032 -1.07978326 -0.31638977  1.18003087]
 [-1.18684214 -0.48756202  0.487543   -2.08153995]
 [ 0.65033511 -0.62126518 -0.38231041  2.16921761]]


In [22]:
print(np.mean(ar, axis = 1)) # an average value among the lines
print(np.mean(ar, axis = 0)) # an average value among the superiors

[ 0.91001267  0.16008454 -0.81710028  0.45399428]
[ 0.34016326 -0.63112177  0.30465861  0.69329112]


Method `cumsum`

In [23]:
array = np.arange(5)
print(np.cumsum(array)) # calculates sum of the previous elements(0 + 1 = 1 => 0 + 1 + 2 = 3 => 0 + 1 + 2 + 3 = 6)

[ 0  1  3  6 10]
