### Data Science and AI Practicum

- Sorting

In [3]:
import numpy as np
array =  np.random.randint(101, size = (1, 20))
print(array)

[[53 76  3 12 49 45 74 15 10 20 33 49 55 68 85 98 55 92 34 71]]


Method `sort`

In [7]:
sorted_array =  np.sort(array) # Copying a sorted array to another array while original is not changed

print(f"{array}\n---------------------------------------------------------------")
print(sorted_array)

[[53 76  3 12 49 45 74 15 10 20 33 49 55 68 85 98 55 92 34 71]]
---------------------------------------------------------------
[[ 3 10 12 15 20 33 34 45 49 49 53 55 55 68 71 74 76 85 92 98]]


In [14]:
array.sort() # Not copying, changing the oringinal array to the sorted one
print(array)

[[ 3 10 12 15 20 33 34 45 49 49 53 55 55 68 71 74 76 85 92 98]]


- Sorting vise versa

In [16]:
vice_versa = -np.sort(-array) # sorting in opposite order
print(vice_versa)

[[98 92 85 76 74 71 68 55 55 53 49 49 45 34 33 20 15 12 10  3]]


- Sorting exact elements

In [ ]:
import numpy as np

In [18]:
arr =  np.random.randint(101, size = (2, 4))
print(arr)

[[78  8 14 69]
 [88 74 29 16]]


In [19]:
line = np.sort(arr, axis = 1) # sorting only the lines not whole array
print(line)

[[ 8 14 69 78]
 [16 29 74 88]]


In [21]:
superior = np.sort(line, axis = 0) # sorting superiors
print(superior)

[[ 8 14 69 78]
 [16 29 74 88]]


### Practice


- Task 1

In [42]:
import numpy as np

arr1_sorted = np.array([95, 92, 88, 85, 78])
arr2_sorted = np.array(["David", "Bob", "Eve", "Alice", "Charlie"])
print(arr1_sorted)
print(arr2_sorted)

s_index = np.argsort(arr1_sorted) # getting indexes of the scores
print(f"----------------------\nIndexes\n{s_index}\n-----------------------")

scores = arr1_sorted[s_index] # sorting arr1_sorted based on indexes
names = arr2_sorted[s_index]  # sorting arr2_sorted based on indexes

print(scores)
print(names)

[95 92 88 85 78]
['David' 'Bob' 'Eve' 'Alice' 'Charlie']
----------------------
Indexes
[4 3 2 1 0]
-----------------------
[78 85 88 92 95]
['Charlie' 'Alice' 'Eve' 'Bob' 'David']
