### Data Science and AI Practicum

Methods: `unique` `in1d` `setdiff1d`

*Method `unique`*

In [1]:
import numpy as np

names = np.array(["Jinwoo", "Kaizen", "Kaizetse", "Yamado", "Miko", "Jinwoo", "Kaizen"])

print(np.unique(names)) # leaves only the ones that do not repeat

['Jinwoo' 'Kaizen' 'Kaizetse' 'Miko' 'Yamado']


In [4]:
ints = np.random.randint(10, size = (1, 11))
print(f"{ints}\n----------------------")
print(np.unique(ints)) # leaves only the ones that do not repeat

[[6 6 8 3 3 1 0 7 0 3 3]]
----------------------
[0 1 3 6 7 8]


*Method `in1d`*

In [11]:
ar =  np.random.randint(11, size = (1, 11))
arr = np.random.randint(11, size = (1, 4))
print(f"{ar}\n{arr}\n-----------------------")
print(np.in1d(ar, arr)) # compares two arrays and returns True if there are the same values in BOTH arrays

[[ 7  5  4  5  2 10  5  7  8  0  5]]
[[5 3 9 3]]
-----------------------
[False  True False  True False False  True False False False  True]


In [12]:
name1 = np.array(["Jinwoo", "Kaizen", "Kaizetse", "Yamado", "Miko", "Jinwoo", "Kaizen"])
name2 = np.array(["Kaizen", "Yamado"])

print(np.in1d(name1, name2))

[False  True False  True False False  True]


*Method `setdiff1d`*

In [14]:
name1 = np.array(["Jinwoo", "Kaizen", "Kaizetse", "Yamado", "Miko", "Jinwoo", "Kaizen"])
name2 = np.array(["Kaizen", "Yamado"])

print(np.setdiff1d(name1, name2)) # compares two arrays and returns the ones that is not in BOTH arrays

['Jinwoo' 'Kaizetse' 'Miko']


In [15]:
name1 = np.array(["Jinwoo", "Kaizen", "Kaizetse", "Yamado", "Miko", "Jinwoo", "Kaizen"])
name2 = np.array(["Kaizen", "Yamado", "Kaizetse"])
print(np.setdiff1d(name1, name2))

['Jinwoo' 'Miko']
