### Data Sciecne

Working with files

`save` `savetxt` `savez` `savez_compressed`

`save` saving in binary

In [5]:
import numpy as np
arr = np.arange(11)
np.save("data", arr)

None


In [7]:
arr1 = np.load("data.npy")
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


`savetxt` saving as a text

In [11]:
arr2 = np.arange(21)
np.savetxt("datatxt", arr2)
ar = np.loadtxt("datatxt")
print(ar)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]


`savez` saving two arrays in one

In [14]:
np.savez("arrays.npy", a = arr, b = arr2)
arrays = np.load("arrays.npz")
print(arrays["a"])
print(arrays["b"])

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


`savez_compressed` saving compressed version

In [22]:
np.savez_compressed("array", d = arr, c = arr2)
array = np.load("array.npz")
print(array["c"])
print(array["d"])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10]
