### Numpy Tasks

1. 1D array yarating va 3-elementni chiqarib oling.
 2. 2D array yarating va [1][2] elementni toping.
 3. 3x4 arraydan oxirgi qatordagi barcha elementlarni oling.
 4. Har bir qatordan 2-elementni chiqarib oling (fancy indexing).
 5. 5x5 array yarating va [0,2,4] qatorlaridagi [1,3] ustunlarni oling.
 6. Arraydagi musbat elementlarni faqat indeks orqali toping.


        2. Slicing
 1. [10, 20, 30, 40, 50, 60] dan [20, 30, 40] ni oling.
 2. 5x5 arraydan markaziy 3x3 bo‘lakni kesib oling.
 3. 1D arraydan har ikkinchi elementni oling.
 4. [::-1] yordamida arrayni teskari aylantiring.
 5. 2D arraydan oxirgi 2 qatordagi birinchi 3 ustunni oling.
 6. Arrayni slicing orqali o‘zgartiring (subarrayni boshqa qiymat bilan almashtiring).


      3. Filtering
 1. [2, 8, -5, 0, 7, -1] dagi musbat elementlarni oling.
 2. 10 dan katta elementlarni tanlang.
 3. Hatto (juft) sonlarni toping.
 4. 2D arraydagi manfiy qiymatlarni toping.
 5. 1D arraydagi 3 va 7 ga karrali sonlarni tanlang.
 6. [True, False, True, False] ni boolean filter sifatida qo‘llang.
 7. Shartga mos kelmaydigan elementlarni 0 bilan almashtiring.


        4. np.where, argwhere, nonzero
 1. [3, 5, 7, 2, 9] arrayda >5 bo‘lgan indekslarni np.where bilan toping.
 2. np.where bilan x > 5 bo‘lsa 1, aks holda 0 qaytaradigan yangi array yarating.
 3. 2D arrayda np.argwhere yordamida 0 bo‘lmagan elementlarning koordinatalarini oling.
 4. np.nonzero orqali x = [0, 1, 0, 2] dagi nol bo‘lmagan indekslarni toping.
 5. np.where bilan 2 ta arrayni shartga qarab birlashtiring (np.where(condition, x, y)).
 6. np.argwhere dan foydalanib: manfiy sonlar joylashgan indekslarni ajrating.


         5. np.any, np.all
 1. [True, False, True] da any va all natijasini hisoblang.
 2. 2D arrayda har bir qatorda kamida 1 ta 0 bor-yo‘qligini tekshiring.
 3. Har bir ustunda faqat musbat sonlar bor-yo‘qligini tekshiring.
 4. Boolean arrayda all yordamida barcha shartlar bajarilganini aniqlang.
 5. x > 5 bo‘lgan sonlar mavjudligini any yordamida tekshiring.

          6. shape, size, ndim, dtype
 1. 3x4 array yaratib, uning .shape, .size, .ndim, .dtype ni chop eting.
 2. 1D va 2D arraylar uchun o‘lchamlarni taqqoslang.
 3. .reshape() yordamida 1D arrayni 2x3 shaklga o‘tkazing.
 4. .dtype o‘zgarishini kuzating (int -> float).
 5. .astype() yordamida float arrayni int arrayga aylantiring.
 6. np.random bilan yaratilgan 3D arrayni .shape orqali tahlil qiling.


7. storega va .nbytes
 1. [1, 2, 3, 4] arrayning .nbytes qiymatini toping.
 2. 2D float array uchun har bir element va umumiy xotira hajmini hisoblang.
 3. .itemsize yordamida element xajmini bilib oling.
 4. Har xil .dtype bilan arraylar yaratib, xotira farqini ko‘ring.
 5. 1000 ta elementli int va float arrayni solishtiring.


8. .transpose(), .T
 1. 3x2 arrayni .T bilan transpozitsiya qiling.
 2. .reshape(2,3,4) qilib, keyin .transpose(1,0,2) qiling.
 3. .T yordamida ustun va qatorlarni almashtiring.
 4. 2D arrayni transpozitsiya qilib, matritsa ko‘rinishini tahlil qiling.
 5. Transpozitsiya qilingan array ustida hisoblash bajaring (dot, sum).


 9. .flat, .tolist(), .real, .imag
 1. .flat yordamida 2D array elementlariga bitta loopda kirib chiqing.
 2. .tolist() yordamida arrayni oddiy Python ro‘yxatiga aylantiring.
 3. Kompleks sonli array yarating va uning .real qismini ajrating.
 4. Yuqoridagi arraydan .imag (tasavvuriy) qismini ajrating.
 5. .flat[index] = value bilan istalgan joydagi qiymatni o‘zgartiring.
 6. .real + .imag orqali kompleks sonni tiklab ko‘ring.
 7. .flat yordamida butun arrayni listga aylantirmasdan o‘qing.


 10. Added
 1. np.clip(x, min, max) yordamida qiymatlarni belgilangan oraliqqa tushiring.
 2. np.unique() yordamida noyob qiymatlarni va ularning sonini hisoblang.
 3. np.isfinite() yordamida np.nan, np.inf larni tekshiring.
 4. np.cumsum() bilan yig‘indi ketma-ketligini yarating.
 5. np.diff() bilan farqlarni toping.
 6. np.sort() va np.argsort() bilan arrayni tartiblang va indekslarini biling.



---





---



### `1`

1

1. 1D array yarating va 3-elementni chiqarib oling.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

 2. 2D array yarating va [1][2] elementni toping.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[1][2]

np.int64(6)

In [ ]:
arr[1][:2] # ?

array([4, 5])

3. 3x4 arraydan oxirgi qatordagi barcha elementlarni oling.

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr[2][:]

array([ 8,  9, 10, 11])

 4. Har bir qatordan 2-elementni chiqarib oling (fancy indexing).


In [ ]:
arr[:, 2]

array([ 2,  6, 10])

 5. 5x5 array yarating va [0,2,4] qatorlaridagi [1,3] ustunlarni oling.

In [ ]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ind = [1, 3]
arr[::2, ind]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

 6. Arraydagi musbat elementlarni faqat indeks orqali toping.

In [ ]:
arr[arr > 0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])



---



---



### `2.Slicing`

 1. [10, 20, 30, 40, 50, 60] dan [20, 30, 40] ni oling.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr[1:4]

array([20, 30, 40])

 2. 5x5 arraydan markaziy 3x3 bo‘lakni kesib oling.

In [ ]:
arr = np.random.randint(1, 100, size = [5, 5])
arr

array([[29, 17, 68, 11, 98],
       [11, 40, 49, 97, 96],
       [32, 90, 77, 72,  4],
       [17, 12, 37, 10, 36],
       [11, 91, 22, 13, 89]])

In [ ]:
arr = arr[:, 1:4]
arr[1:4, :]

array([[40, 49, 97],
       [90, 77, 72],
       [12, 37, 10]])

 3. 1D arraydan har ikkinchi elementni oling.

In [ ]:
arr = np.arange(11)
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

4. [::-1] yordamida arrayni teskari aylantiring.

In [ ]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 5. 2D arraydan oxirgi 2 qatordagi birinchi 3 ustunni oling.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [7, 8, 9, 10, 11], [11, 12, 13, 14, 15]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11],
       [11, 12, 13, 14, 15]])

In [ ]:
arr[-2:, :3]

array([[ 7,  8,  9],
       [11, 12, 13]])



---



---



###       `3. Filtering`


 1. [2, 8, -5, 0, 7, -1] dagi musbat elementlarni oling.

In [ ]:
arr = np.array([2, 8, -5, 0, 7, -1])
arr

array([ 2,  8, -5,  0,  7, -1])

In [ ]:
arr[arr > 0]

array([2, 8, 7])

2. 3 dan katta elementlarni tanlang.

In [ ]:
arr[arr > 3]

array([8, 7])

3. Hatto (juft) sonlarni toping.

In [ ]:
arr[arr % 2 == 0]

array([2, 8, 0])

 4. 2D arraydagi manfiy qiymatlarni toping.

In [ ]:
arr[arr < 0]

array([-5, -1])

 5. 1D arraydagi 3 va 7 ga karrali sonlarni tanlang.

In [ ]:
arr = np.arange(0, 100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
arr[(arr % 3 == 0) & (arr % 7 == 0)]

array([ 0, 21, 42, 63, 84])

 6. [True, False, True, False] ni boolean filter sifatida qo‘llang.

In [ ]:
arr = np.array([1, 2, 3, 4])
arr[[True, False, True, False]]

array([1, 3])

 7. Shartga mos kelmaydigan elementlarni 0 bilan almashtiring.

In [ ]:
arr = np.where(arr % 2 == 0, 1, 0)
arr

array([0, 1, 0, 1])

In [ ]:
arr = np.array([1, 2, 3, 4])
arr[arr % 2 == 1] = 0
arr

array([0, 2, 0, 4])



---



---



### `4. np.where, argwhere, nonzero `

 1. [3, 5, 7, 2, 9] arrayda >5 bo‘lgan indekslarni np.where bilan toping.

In [ ]:
arr = np.array([3, 5, 7, 2, 9])
np.where(arr > 5, 'B', 'S')

array(['S', 'S', 'B', 'S', 'B'], dtype='<U1')

In [ ]:
arr[arr > 5]

array([7, 9])

 2. np.where bilan x > 5 bo‘lsa 1, aks holda 0 qaytaradigan yangi array yarating.

In [ ]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.where(arr > 5, 1, 0)


array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

 3. 2D arrayda np.argwhere yordamida 0 bo‘lmagan elementlarning koordinatalarini oling.

In [ ]:
arr = np.array([[1, 2, 0], [4, 0, 6]])
np.argwhere(arr)

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 2]])

 4. np.nonzero orqali x = [0, 1, 0, 2] dagi nol bo‘lmagan indekslarni toping.


In [ ]:
arr = np.array([0, 1, 0, 2])
arr

array([0, 1, 0, 2])

In [ ]:
np.nonzero(arr)

(array([1, 3]),)

In [ ]:
arr[np.nonzero(arr)]

array([1, 2])

 5. np.where bilan 2 ta arrayni shartga qarab birlashtiring (np.where(condition, x, y)).

In [ ]:
arr = np.array([1, 2, 3])
arr1 = np.array([4, 5, 6])
res = np.concatenate((np.where(arr % 2 == 1, arr, 0), np.where(arr1 % 2 == 0, arr1, 0)))
res

array([1, 0, 3, 4, 0, 6])

In [ ]:
res[np.nonzero(res)]

array([1, 3, 4, 6])

 6. np.argwhere dan foydalanib: manfiy sonlar joylashgan indekslarni ajrating.


In [ ]:
arr = np.random.randn(3, 3)
arr

array([[-0.55655733,  0.40972276,  1.80195207],
       [ 0.81532127, -0.37804398, -0.02593401],
       [ 0.23347293, -0.4894717 , -0.67493373]])

In [ ]:
np.argwhere(arr)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])



---



---



### `5. np.any, np.all`


 1. [True, False, True] da any va all natijasini hisoblang.

In [ ]:
np.all(arr[True, True, True, False])

np.True_

 3. Har bir ustunda faqat musbat sonlar bor-yo‘qligini tekshiring.


In [ ]:
arr = np.array([[1, -2, 3], [4, 5, 6]])
np.all(arr > 0, axis = 1)

array([False,  True])

 4. Boolean arrayda all yordamida barcha shartlar bajarilganini aniqlang.


In [ ]:
arr = np.array([[1, -2, 3], [-4, 5, 6]])
np.all(arr > 0)

np.False_

 5. x > 5 bo‘lgan sonlar mavjudligini any yordamida tekshiring.


In [ ]:
arr = np.random.randint(10, size = [10])
arr

array([7, 4, 5, 1, 0, 1, 8, 6, 1, 2])

In [ ]:
np.any(arr > 5)

np.True_



---



---




`6. shape, size, ndim, dtype`

 1. 3x4 array yaratib, uning .shape, .size, .ndim, .dtype ni chop eting.


In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr.ndim

2

In [ ]:
arr.dtype

dtype('int64')

 2. 1D va 2D arraylar uchun o‘lchamlarni taqqoslang.


In [ ]:
arr = np.array([1, 2, 3])
arr1 = np.array([[1,2, 3], [4, 5, 6]])
print(arr.ndim)
print(arr1.ndim)

1
2


 3. .reshape() yordamida 1D arrayni 2x3 shaklga o‘tkazing.


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

 4. .dtype o‘zgarishini kuzating (int -> float).


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = arr.astype(np.float16)
arr.dtype

dtype('float16')

 5. .astype() yordamida float arrayni int arrayga aylantiring.


In [ ]:
arr = np.array([1.5, 2.4, 6.5])
arr.astype(np.int8)

array([1, 2, 6], dtype=int8)

 6. np.random bilan yaratilgan 3D arrayni .shape orqali tahlil qiling.


In [ ]:
arr = np.random.randint(10, size = [2, 3, 4])
arr

array([[[3, 7, 2, 3],
        [0, 1, 5, 2],
        [3, 6, 5, 3]],

       [[9, 0, 5, 3],
        [7, 3, 8, 2],
        [4, 7, 9, 2]]])

In [ ]:
arr.shape

(2, 3, 4)



---



---



`7. storega va .nbytes `

 1. [1, 2, 3, 4] arrayning .nbytes qiymatini toping.


In [ ]:
arr = np.array([1, 2, 3, 4])
arr.nbytes

32

 2. 2D float array uchun har bir element va umumiy xotira hajmini hisoblang.


`nbytes` total memory `itemsize` byte per element

In [ ]:
arr = np.arange(6).reshape(2, 3)
arr.itemsize

8

In [ ]:
arr.nbytes

48

 3. .itemsize yordamida element xajmini bilib oling.


In [ ]:
arr = np.arange(6).reshape(2, 3)
arr.itemsize

8

 4. Har xil .dtype bilan arraylar yaratib, xotira farqini ko‘ring.


In [ ]:
arr = np.random.rand(2, 3)
arr.itemsize

8

In [ ]:
arr = np.array(['1', '2', '3'])
arr.itemsize

4

In [ ]:
arr = np.random.randint(50, 100, size = [2, 3])
arr.itemsize

8



---



---



`8. .transpose(), .T`

 1. 3x2 arrayni .T bilan transpozitsiya qiling.

In [ ]:
import numpy as np
arr = np.arange(6).reshape(3, 2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr.T

array([[0, 2, 4],
       [1, 3, 5]])

 2. .reshape(2,3,4) qilib, keyin .transpose(1,0,2) qiling.


In [ ]:
arr = np.random.rand(2, 3, 4)
arr

array([[[0.45959181, 0.27282362, 0.2919609 , 0.33195744],
        [0.3035917 , 0.38878276, 0.05692572, 0.19887377],
        [0.28535937, 0.42714711, 0.33899869, 0.69308585]],

       [[0.3403526 , 0.19884874, 0.81391539, 0.64027794],
        [0.35780533, 0.42310543, 0.27123829, 0.54488192],
        [0.62562286, 0.68945862, 0.96143304, 0.52923564]]])

In [ ]:
arr.transpose(1, 0, 2)

array([[[0.45959181, 0.27282362, 0.2919609 , 0.33195744],
        [0.3403526 , 0.19884874, 0.81391539, 0.64027794]],

       [[0.3035917 , 0.38878276, 0.05692572, 0.19887377],
        [0.35780533, 0.42310543, 0.27123829, 0.54488192]],

       [[0.28535937, 0.42714711, 0.33899869, 0.69308585],
        [0.62562286, 0.68945862, 0.96143304, 0.52923564]]])


 3. .T yordamida ustun va qatorlarni almashtiring.


In [ ]:
arr = np.arange(6).reshape(3, 2)
arr.T.shape # 3, 2

(2, 3)

 4. 2D arrayni transpozitsiya qilib, matritsa ko‘rinishini tahlil qiling.


In [ ]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = arr.T

 5. Transpozitsiya qilingan array ustida hisoblash bajaring (dot, sum).


In [ ]:
arr.sum()

np.int64(15)

In [ ]:
arr.dot(b = 4)

array([[ 0, 12],
       [ 4, 16],
       [ 8, 20]])



---



---



 9. .flat, .tolist(), .real, .imag

 1. .flat yordamida 2D array elementlariga bitta loopda kirib chiqing.


In [ ]:
new = []
for i in arr.flat:
  i += 4
  new.append(i)

In [ ]:
arr = np.array(new)
arr

array([4, 7, 5, 8, 6, 9])

 2. .tolist() yordamida arrayni oddiy Python ro‘yxatiga aylantiring.


In [ ]:
arr.tolist()

[4, 7, 5, 8, 6, 9]

 3. Kompleks sonli array yarating va uning .real qismini ajrating.


In [ ]:
arr = np.array([2 + 2j, 4 +8j])
arr.imag

array([2., 8.])

In [ ]:
arr.real

array([2., 4.])

 4. Yuqoridagi arraydan .imag (tasavvuriy) qismini ajrating.


In [ ]:
arr.imag

array([2., 8.])

 5. .flat[index] = value bilan istalgan joydagi qiymatni o‘zgartiring.


In [ ]:
arr = np.array([1, 2, 3, 4])
res = []
for i in arr.flat:
  if i % 2 == 0:
    i = i + 2

  res.append(i)
arr = np.array(res)

In [ ]:
arr

array([1, 4, 3, 6])

 6. .real + .imag orqali kompleks sonni tiklab ko‘ring.


In [ ]:
arr = np.array([2 + 2j, 4 + 8j])
im = arr.imag
re = arr.real
print(im)
print(re)

[2. 8.]
[2. 4.]


 7. .flat yordamida butun arrayni listga aylantirmasdan o‘qing.


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
for i in arr.flat:
  print(i)

1
2
3
4
5
6




---



---



 10. Added


 1. np.clip(x, min, max) yordamida qiymatlarni belgilangan oraliqqa tushiring.
 2. np.unique() yordamida noyob qiymatlarni va ularning sonini hisoblang.
 3. np.isfinite() yordamida np.nan, np.inf larni tekshiring.
 4. np.cumsum() bilan yig‘indi ketma-ketligini yarating.
 5. np.diff() bilan farqlarni toping.
 6. np.sort() va np.argsort() bilan arrayni tartiblang va indekslarini biling.

 1. np.clip(x, min, max) yordamida qiymatlarni belgilangan oraliqqa tushiring.


In [ ]:
arr = np.clip(arr, 1, 10)
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

 2. np.unique() yordamida noyob qiymatlarni va ularning sonini hisoblang.


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 3, 4])
arr = np.unique(arr)
arr

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1, 2, 2])
np.unique(a)

array([1, 2])

 3. np.isfinite() yordamida np.nan, np.inf larni tekshiring.


In [ ]:
arr = np.array([1, 2, 3, np.nan, 4, np.nan])
np.isfinite(arr)

array([ True,  True,  True, False,  True, False])

 4. np.cumsum() bilan yig‘indi ketma-ketligini yarating.


In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.cumsum(arr, axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])