### Numpy Recap

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3, 4, 5, 6])
array1

array([1, 2, 3, 4, 5, 6])

In [ ]:
names = np.array(['Makima', 'Bea', 'Alex', 'Zenizu'])
names

array(['Makima', 'Bea', 'Alex', 'Zenizu'], dtype='<U6')

In [ ]:
print(names)

['Makima' 'Bea' 'Alex' 'Zenizu']


In [ ]:
type(names)

numpy.ndarray

### Len of an Array

`.ndim`

In [ ]:
names.ndim

1

### 0D array

In [ ]:
ar0 = np.array(24)
print(ar0)
print(ar0.ndim)

24
0


### 1D array

In [ ]:
ar1 = np.array([1, 2, 3, 4, 5])
print(ar1)
print(ar1.ndim)

[1 2 3 4 5]
1


### 2D array

In [ ]:
ar2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


### 3D array

In [ ]:
ar3 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
3


### `zeros` `ones` `shape` `size` `arange`

In [ ]:
shap = np.zeros(shape = (3, 3))
shap

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
shap1 = np.ones(shape = (3, 4))
shap1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
print(shap.shape)

(3, 3)


In [ ]:
print(shap1.size)

12


In [ ]:
arange = np.arange(21)
print(arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arange1 = np.arange(0, 100, 5)
arange1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

`Reshape` 'Full'

In [ ]:
resh = np.arange(12).reshape(3, 4)
resh

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
resh2 = np.arange(0, 36, 2).reshape(3, 6)
resh2

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34]])

In [ ]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.full((10), 'I love you')

array(['I love you', 'I love you', 'I love you', 'I love you',
       'I love you', 'I love you', 'I love you', 'I love you',
       'I love you', 'I love you'], dtype='<U10')

### Data Type


int8: 8-bit signed integer (-128 to 127).

int16: 16-bit signed integer (-32,768 to 32,767).

int32: 32-bit signed integer (-2,147,483,648 to 2,147,483,647).

int64: 64-bit signed integer (-9,223,372,036,854,775,808 to 9,223,372,036,854,775,807).

uint8: 8-bit unsigned integer (0 to 255).

uint16: 16-bit unsigned integer (0 to 65,535).

uint32: 32-bit unsigned integer (0 to 4,294,967,295).

uint64: 64-bit unsigned integer (0 to 18,446,744,073,709,551,615).

float16: 16-bit floating point.

float32: 32-bit floating point.

float64: 64-bit floating point (double precision).

complex64: Complex number with 32-bit real and imaginary parts.

complex128: Complex number with 64-bit real and imaginary parts.

bool: Boolean type (True or False).

str: String (sequence of characters).

`dtype` checks the data type but `astype`  converts the data to an exact type

In [ ]:
ar = np.array([1, 2, 3, 4, 5], dtype = np.int8)
print(ar)
print(ar.dtype)

[1 2 3 4 5]
int8


In [ ]:
ar = ar.astype(np.int16)
print(ar)
print(ar.dtype)

[1 2 3 4 5]
int16


In [ ]:
arrr = np.array([1, 1.0])
print(arrr.dtype)

float64


In [ ]:
arrr.astype(np.int8)

array([1, 1], dtype=int8)

### Indexe / Slicing

In [ ]:
ind = np.arange(40).reshape(4, 10)
ind

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
sliced = ind[0][5:7]
sliced

array([5, 6])

In [ ]:
sliced = ind[3][-3:]
sliced

array([37, 38, 39])

`copy`

In [ ]:
copy = ind[2][-5:-2].copy()
copy

array([25, 26, 27])

### Random in Numpy

In [ ]:
rand = np.random.rand(12).reshape(3, 4)
rand

array([[0.20529082, 0.16186748, 0.54921652, 0.98952617],
       [0.85447171, 0.09421623, 0.45255292, 0.35878448],
       [0.41613722, 0.6014133 , 0.72179447, 0.27754662]])

In [ ]:
randin = np.random.randint(0, 100, size = 12).reshape(4, 3)
randin

array([[62, 96, 84],
       [12, 80, 50],
       [55, 71, 35],
       [44, 95, 62]])

In [ ]:
ran = np.random.randint(0, 100, size = 40).reshape(4, 10)
new = np.array([])
for num in ran:
  for i in num:
    if i % 2 == 0:
      new = np.append(new, num)
new

array([40., 66., 21., 62., 58., 43., 13., 22.,  6., 86., 40., 66., 21.,
       62., 58., 43., 13., 22.,  6., 86., 40., 66., 21., 62., 58., 43.,
       13., 22.,  6., 86., 40., 66., 21., 62., 58., 43., 13., 22.,  6.,
       86., 40., 66., 21., 62., 58., 43., 13., 22.,  6., 86., 40., 66.,
       21., 62., 58., 43., 13., 22.,  6., 86., 40., 66., 21., 62., 58.,
       43., 13., 22.,  6., 86., 82.,  9., 39., 15., 23., 37., 11., 34.,
       52.,  4., 82.,  9., 39., 15., 23., 37., 11., 34., 52.,  4., 82.,
        9., 39., 15., 23., 37., 11., 34., 52.,  4., 82.,  9., 39., 15.,
       23., 37., 11., 34., 52.,  4., 25., 18., 79., 99., 95., 90., 64.,
       86., 58., 28., 25., 18., 79., 99., 95., 90., 64., 86., 58., 28.,
       25., 18., 79., 99., 95., 90., 64., 86., 58., 28., 25., 18., 79.,
       99., 95., 90., 64., 86., 58., 28., 25., 18., 79., 99., 95., 90.,
       64., 86., 58., 28., 25., 18., 79., 99., 95., 90., 64., 86., 58.,
       28., 51., 81.,  5., 29., 33., 48., 42., 25., 78., 88., 51

In [ ]:
ran[ran % 2 == 0]

array([40, 66, 62, 58, 22,  6, 86, 82, 34, 52,  4, 18, 90, 64, 86, 58, 28,
       48, 42, 78, 88])

In [ ]:
ran[ran % 2 == 1]

array([21, 43, 13,  9, 39, 15, 23, 37, 11, 25, 79, 99, 95, 51, 81,  5, 29,
       33, 25])

### Sting + Float

In [ ]:
name = np.array(["Jinwoo", "Levi", "Bibi", "Igris", "Kaizen"])
name

array(['Jinwoo', 'Levi', 'Bibi', 'Igris', 'Kaizen'], dtype='<U6')

In [ ]:
data = np.random.randint(0, 10, size = 20).reshape(5, 4)
data

array([[6, 8, 8, 9],
       [9, 0, 5, 5],
       [2, 1, 2, 7],
       [1, 4, 0, 2],
       [2, 2, 7, 1]])

In [ ]:
print(name == 'Bibi')

[False False  True False False]


In [ ]:
print(data[name == 'Jinwoo'])

[[6 8 8 9]]


In [ ]:
print(data[name == 'Kaizen'])

[[2 2 7 1]]


Slice

In [ ]:
print(data[name == 'Levi', -2:])

[[5 5]]


### Practice

Task 1: Temperature Filtering
Given: A NumPy array of daily temperatures.
Do:

- Filter values above 30°C.

- Replace all negative values with 0.

- Count days with temperature > 25°C.


In [ ]:
temp = [23, 43, 12, 32, -1, 14, 54, -3, 34, -9, 21]
tempo = np.array(temp)
print(f'Temperature over the last 12 days \n{tempo}')

Temperature over the last 12 days 
[23 43 12 32 -1 14 54 -3 34 -9 21]


In [ ]:
highest = tempo > 30
tem = tempo[highest]
tem

array([43, 32, 54, 34])

In [ ]:
tempo[tempo < 0] = 0
tempo

array([23, 43, 12, 32,  0, 14, 54,  0, 34,  0, 21])

In [ ]:
low = tempo[tempo > 25]
print(f'Days count when temp > 25: {len(low)}')

Days count when temp > 25: 4


✅ Task 2: Daily Sales Analysis Given: A NumPy array of sales amounts over 15 days.


- Find how many days sales were above 1000.

- Replace all sales below 100 with 0.

- Count total revenue.

In [ ]:
days = [1200, 9000, 200, 30, 5000, 16000, 2000, 100, 400, 1000, 15, 19000, 10000, 40, 600]
day = np.array(days)
coun = day[day > 1000]
day[day <= 100] = 0
sums = day.sum()
print(f'Amount of days with more than 1000 prof: {len(coun)}')
print(f'Total Revenue: {sums}')

Amount of days with more than 1000 prof: 7
Total Revenue: 64400


### Mathematics

In [ ]:
sum = tempo.sum()
sum

np.int64(233)

### Boolean Operations

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(5)
arr[[True, True, False, True, False]]

array([0, 1, 3])

In [ ]:
arr[arr >= 3]

array([3, 4])

Returns bolean, `True` if the cond is True `False` if con is False

In [ ]:
arr <= 3

array([ True,  True,  True,  True, False])

In [ ]:
arr[arr > arr.mean()]

array([3, 4])

In [ ]:
arr[(arr == 0) | (arr == 4)]

array([0, 4])