# **Data Science and AI Practicum**

## Data analysis. Numpy library.

# **1-PRACTICAL TASK**

## Creating N-dimensional arrays

In [ ]:
import numpy as np

### Task(1): Creating 1-dimensional arrays

**Condition of matter:** Continue with the function that creates a 1-dimensional array with an arbitrary *n* elements (*n* > 0, integer).
**Support :** Use the functions `array` or `random`.


In [25]:
import numpy as np
def one_dim(n):
  if n < 0:
    print("No negativ")
    return None

  array = np.random.randint(0, 100, size= n)
  return array
print(one_dim(16))

[70 26 99  9 59 89 96 55 69 21 34 67  6 87 72 32]


### To test the function you wrote above, navigate to the following cell.

In [24]:
#@title Checking (no errors should occur as a result)
"""Check that function returns the correct output for several inputs"""
for i in range(1, 10):
  assert len(one_dim(i)) == i, f"no errors should occur as a result"
  arr = one_dim(i) # massiv
  assert arr.ndim == 1, f"1-o'lchamli massiv aniqlanmadi"# len of the array
  assert type(arr) == np.ndarray, f"array not defined" #numpy array

_____

### Task(2) Creating 2-dimensional arrays

**Task :** Shape `shape(r, c)` Continue the function that creates a 2-dimensional array.

**Support :** You can use any of the array creation functions in the numpy library.


In [17]:
import numpy as np
def two_dim(r, c):
  arr1 = np.ones(shape=(r, c))
  return arr1

print(two_dim(2, 3))

[[1. 1. 1.]
 [1. 1. 1.]]


### To test the function you wrote above, navigate to the following cell.

In [22]:
#@title Checking (no errors should occur as a result)
"""Check that function returns the correct output for several inputs"""
arr = two_dim(3, 2) # array
assert arr.shape == (3, 2), f"no errors should occur as a result" # shape
assert arr.ndim == 2, f"2-dimensional array not defined" # len of the array
assert type(arr) == np.ndarray, f"array not defined"# #numpy array